--create type data clientes--

USE TallerDatabase
CREATE TYPE NIF_type FROM CHAR(9) NOT NULL
CREATE TYPE Nombre_type FROM VARCHAR(30) NOT NULL
CREATE TYPE Apellido1_type FROM VARCHAR(50) NOT NULL
CREATE TYPE Apellido2_type FROM VARCHAR(50) NOT NULL
CREATE TYPE Direccion_type FROM VARCHAR(100) NOT NULL
CREATE TYPE Poblacion_type FROM VARCHAR (60)NOT NULL
CREATE TYPE CP_type FROM CHAR(5) NOT NULL
CREATE TYPE Telefono_type FROM VARCHAR(12) NOT NULL
CREATE TYPE Correo_type FROM VARCHAR(100) NOT NULL;

--create type data vehiculos--

USE TallerDatabase
CREATE TYPE Matricula_type FROM VARCHAR(8) NOT NULL
CREATE TYPE Marca_type FROM VARCHAR(25) NOT NULL
CREATE TYPE Modelo_type FROM VARCHAR(25) NOT NULL
CREATE TYPE YearMatriculacion_type FROM CHAR(4)  NOT NULL
CREATE TYPE Kilometraje_type FROM INT  NOT NULL
CREATE TYPE Combustible_type FROM VARCHAR(9) NOT NULL
CREATE TYPE TipoCambio_type FROM VARCHAR(10) NOT NULL
CREATE TYPE PotenciaMotor_type FROM SMALLINT  NOT NULL
CREATE TYPE ClienteID_type FROM INT  NOT NULL

--create type data reparaciones--

USE TallerDatabase
CREATE TYPE FechaReparacion_type FROM DATE NOT NULL
CREATE TYPE Descripcion_type FROM VARCHAR(255) NOT NULL
CREATE TYPE ValorMateriales_type FROM DECIMAL(10,2) NOT NULL
CREATE TYPE HorasReparacion_type FROM DECIMAL(10,2) 
CREATE TYPE FacturaID_type FROM INT 

--create type data facturas--

USE TallerDatabase
CREATE TYPE FechaFactura_type FROM DATE NOT NULL
CREATE TYPE ImporteSinIVA_type FROM DECIMAL (10,2) NOT NULL
CREATE TYPE IVA_type FROM DECIMAL (10,2) NOT NULL
CREATE TYPE ImporteConIVA_type FROM DECIMAL (10,2) NOT NULL

